version: '3.8'

services:
  figgy-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: figgy-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - secretKey=secretKey
      - EMAIL=EMAIL
      - MongoDb_Connection_String=${MONGODB_CONNECTION_STRING}
    volumes:
      - ./backend/storage:/app/storage
    restart: unless-stopped
    networks:
      - figgy-network

networks:
  figgy-network:
    driver: bridge


